
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author YahMa
 */
public class ConfigureForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigureForm
     */
    public JRadioButton[][] radioBtns;
    private int questNum;
    private int boxNum;
    private Hashtable<String, Integer> weights;
    Hashtable<String, StudentIFATCard> studentCardTable;
    private String backFolderPath;
    private int[] answerKey;

    public ConfigureForm() {
        initComponents();
    }

    public ConfigureForm(String path, Hashtable<String, StudentIFATCard> cards) {
        initComponents();
        backFolderPath = path;
        studentCardTable = cards;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        pnl_Param = new javax.swing.JPanel();
        lbl_Param = new javax.swing.JLabel();
        lbl_Questions = new javax.swing.JLabel();
        lbl_Boxes = new javax.swing.JLabel();
        txt_Questions = new javax.swing.JTextField();
        spn_Boxes = new javax.swing.JSpinner();
        btn_Confirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_Custom = new javax.swing.JLabel();
        lbl_Att1 = new javax.swing.JLabel();
        txt_Att1 = new javax.swing.JTextField();
        lbl_Att2 = new javax.swing.JLabel();
        txt_Att2 = new javax.swing.JTextField();
        lbl_Att3 = new javax.swing.JLabel();
        txt_Att3 = new javax.swing.JTextField();
        lbl_Att4 = new javax.swing.JLabel();
        txt_Att4 = new javax.swing.JTextField();
        lbl_Att5 = new javax.swing.JLabel();
        txt_Att5 = new javax.swing.JTextField();
        btn_Custom = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        btn_Grade = new javax.swing.JButton();
        pnl_AnsContainer = new javax.swing.JPanel();
        lbl_AnsTitle = new javax.swing.JLabel();
        scr_Ans = new javax.swing.JScrollPane();
        pnl_AnsKey = new javax.swing.JPanel();
        btn_Set = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure the Grading application");

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Title.setText("Configure Grader");

        pnl_Param.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Param.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Param.setText("Configure the parameters of the assesment");

        lbl_Questions.setText("Enter the number of questions:");

        lbl_Boxes.setText("Enter the number of boxes:");

        txt_Questions.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Questions.setText("10");
        txt_Questions.setName("txt_Questions"); // NOI18N

        spn_Boxes.setModel(new javax.swing.SpinnerNumberModel(5, 3, 5, 1));
        spn_Boxes.setName("spn_Boxes"); // NOI18N

        btn_Confirm.setText("Confirm");
        btn_Confirm.setName("btn_Confirm"); // NOI18N
        btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ParamLayout = new javax.swing.GroupLayout(pnl_Param);
        pnl_Param.setLayout(pnl_ParamLayout);
        pnl_ParamLayout.setHorizontalGroup(
            pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ParamLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Param)
                    .addGroup(pnl_ParamLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Questions, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lbl_Boxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Questions)
                            .addComponent(spn_Boxes))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnl_ParamLayout.setVerticalGroup(
            pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ParamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Param)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Questions)
                    .addComponent(txt_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Boxes)
                    .addComponent(spn_Boxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_Confirm)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Custom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Custom.setText("Custom Grading Schema");

        lbl_Att1.setText("1st attempt grade:");

        txt_Att1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Att1.setText("100");
        txt_Att1.setName("txt_Att1"); // NOI18N

        lbl_Att2.setText("2nd attempt grade:");

        txt_Att2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Att2.setText("66");
        txt_Att2.setName("txt_Att2"); // NOI18N
        txt_Att2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Att2ActionPerformed(evt);
            }
        });

        lbl_Att3.setText("3rd attempt grade:");

        txt_Att3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Att3.setText("33");
        txt_Att3.setName("txt_Att3"); // NOI18N
        txt_Att3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Att3ActionPerformed(evt);
            }
        });

        lbl_Att4.setText("4th attempt grade:");

        txt_Att4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Att4.setText("25");
        txt_Att4.setName("txt_Att4"); // NOI18N
        txt_Att4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Att4ActionPerformed(evt);
            }
        });

        lbl_Att5.setText("5th attempt grade:");

        txt_Att5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Att5.setText("0");
        txt_Att5.setName("txt_Att5"); // NOI18N
        txt_Att5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Att5ActionPerformed(evt);
            }
        });

        btn_Custom.setText("Confirm");
        btn_Custom.setName("btn_Custom"); // NOI18N
        btn_Custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Att1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Att1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Custom)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Att5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Att5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Att4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Att4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Att3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Att3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Att2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Att2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Custom, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Custom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Att1)
                    .addComponent(txt_Att1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Att2)
                    .addComponent(txt_Att2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Att3)
                    .addComponent(txt_Att3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Att4)
                    .addComponent(txt_Att4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Att5)
                    .addComponent(txt_Att5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Custom)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btn_Back.setText("Back");
        btn_Back.setName("btn_Back"); // NOI18N
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");
        btn_Exit.setName("btn_Exit"); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Grade.setText("Grade");
        btn_Grade.setEnabled(false);
        btn_Grade.setName("btn_Grade"); // NOI18N
        btn_Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GradeActionPerformed(evt);
            }
        });

        pnl_AnsContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_AnsContainer.setName("pnl_AnsContainer"); // NOI18N

        lbl_AnsTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_AnsTitle.setText("Enter the answer key");

        scr_Ans.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scr_Ans.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout pnl_AnsKeyLayout = new javax.swing.GroupLayout(pnl_AnsKey);
        pnl_AnsKey.setLayout(pnl_AnsKeyLayout);
        pnl_AnsKeyLayout.setHorizontalGroup(
            pnl_AnsKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        pnl_AnsKeyLayout.setVerticalGroup(
            pnl_AnsKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        scr_Ans.setViewportView(pnl_AnsKey);

        btn_Set.setText("Set Answer key");
        btn_Set.setName("btn_Set"); // NOI18N
        btn_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_AnsContainerLayout = new javax.swing.GroupLayout(pnl_AnsContainer);
        pnl_AnsContainer.setLayout(pnl_AnsContainerLayout);
        pnl_AnsContainerLayout.setHorizontalGroup(
            pnl_AnsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AnsContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_AnsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scr_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AnsContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Set)
                .addGap(19, 19, 19))
        );
        pnl_AnsContainerLayout.setVerticalGroup(
            pnl_AnsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AnsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_AnsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Set)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_Param, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnl_AnsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Exit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Back)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Grade)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbl_Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_Param, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_AnsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back)
                    .addComponent(btn_Exit)
                    .addComponent(btn_Grade))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Att2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Att2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Att2ActionPerformed

    private void txt_Att3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Att3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Att3ActionPerformed

    private void txt_Att4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Att4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Att4ActionPerformed

    private void txt_Att5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Att5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Att5ActionPerformed

    private void btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmActionPerformed
        try {
            questNum = Integer.parseInt(txt_Questions.getText());
            boxNum = (int) spn_Boxes.getValue();
            pnl_AnsKey.removeAll();
            GridLayout gl = new GridLayout(questNum, boxNum + 1, 5, 5);
            pnl_AnsKey.setLayout(gl);
            radioBtns = new JRadioButton[questNum][boxNum];

            for (int i = 0; i < questNum; i++) {
                ButtonGroup rdbGroup = new ButtonGroup();
                JLabel lbl_qNum = new JLabel();
                lbl_qNum.setText("Question " + (i + 1) + ": ");
                pnl_AnsKey.add(lbl_qNum);
                for (int j = 0; j < boxNum; j++) {

                    if (j == 0) {
                        radioBtns[i][j] = new JRadioButton("A");
                    }
                    if (j == 1) {
                        radioBtns[i][j] = new JRadioButton("B");
                    }
                    if (j == 2) {
                        radioBtns[i][j] = new JRadioButton("C");
                    }
                    if (j == 3) {
                        radioBtns[i][j] = new JRadioButton("D");
                    }
                    if (j == 4) {
                        radioBtns[i][j] = new JRadioButton("E");
                    }
                    rdbGroup.add(radioBtns[i][j]);
                    pnl_AnsKey.add(radioBtns[i][j]);
                }
            }
            pnl_AnsKey.revalidate();
            pnl_AnsKey.repaint();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_ConfirmActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_CustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomActionPerformed
        try {
            weights = new Hashtable<>();
            int firstAtt = Integer.parseInt(txt_Att1.getText());
            int secondAtt = Integer.parseInt(txt_Att2.getText());
            int thirdAtt = Integer.parseInt(txt_Att3.getText());
            int fourthAtt = Integer.parseInt(txt_Att4.getText());
            int fifthAtt = Integer.parseInt(txt_Att5.getText());

            weights.put("Attempt 1", firstAtt);
            weights.put("Attempt 2", secondAtt);
            weights.put("Attempt 3", thirdAtt);
            weights.put("Attempt 4", fourthAtt);
            weights.put("Attempt 5", fifthAtt);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_CustomActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        close();
        LoadingForm lf = new LoadingForm(backFolderPath);
        lf.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SetActionPerformed
        answerKey = setAnswerKey();
        btn_Grade.setEnabled(true);
    }//GEN-LAST:event_btn_SetActionPerformed

    private void btn_GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GradeActionPerformed
        Enumeration<String> en = studentCardTable.keys();
        if (weights == null) {
            weights = new Hashtable<>();
            weights.put("Attempt 1", 100); // attempt 1 gets 100%
            weights.put("Attempt 2", 66); // attempt 2 gets 66%
            weights.put("Attempt 3", 33); // attempt 3 gets 33%
            weights.put("Attempt 4", 25); // attempt 4 gets 25%
            weights.put("Attempt 5", 0); // attempt 5 gets 0%
        }
        while (en.hasMoreElements()) {
            String key = en.nextElement();
            studentCardTable.get(key).setNumBoxes(boxNum);
            studentCardTable.get(key).setNumQuestions(questNum);
            studentCardTable.get(key).setWeights(weights);
        }
        close();
        GradeConfirmationForm gc = new GradeConfirmationForm(backFolderPath,
                 studentCardTable, answerKey, questNum, boxNum);
        gc.setVisible(true);
    }//GEN-LAST:event_btn_GradeActionPerformed
    // method to set the answer key
    public int[] setAnswerKey() {
        int[] answers = new int[questNum];
        for (int i = 0; i < questNum; i++) {
            for (int j = 0; j < boxNum; j++) {
                if (radioBtns[i][j].isSelected()) {
                    answers[i] = j;
                }
            }
        }
        return answers;
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigureForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigureForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JButton btn_Custom;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Grade;
    private javax.swing.JButton btn_Set;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AnsTitle;
    private javax.swing.JLabel lbl_Att1;
    private javax.swing.JLabel lbl_Att2;
    private javax.swing.JLabel lbl_Att3;
    private javax.swing.JLabel lbl_Att4;
    private javax.swing.JLabel lbl_Att5;
    private javax.swing.JLabel lbl_Boxes;
    private javax.swing.JLabel lbl_Custom;
    private javax.swing.JLabel lbl_Param;
    private javax.swing.JLabel lbl_Questions;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pnl_AnsContainer;
    private javax.swing.JPanel pnl_AnsKey;
    private javax.swing.JPanel pnl_Param;
    private javax.swing.JScrollPane scr_Ans;
    private javax.swing.JSpinner spn_Boxes;
    private javax.swing.JTextField txt_Att1;
    private javax.swing.JTextField txt_Att2;
    private javax.swing.JTextField txt_Att3;
    private javax.swing.JTextField txt_Att4;
    private javax.swing.JTextField txt_Att5;
    private javax.swing.JTextField txt_Questions;
    // End of variables declaration//GEN-END:variables
}
