
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author YahMa
 */
public class DisplayGradeForm extends javax.swing.JFrame {

    Hashtable<String, StudentIFATCard> studentCardTable;
    private int questNum;
    private int boxNum;
    int[] answerKey;
    private String folderPath;
    private String filename;
    public JLabel[][] labels;
    BufferedImage imgCard;

    DefaultTreeModel cardTreeModel;
    DefaultMutableTreeNode cardList = new DefaultMutableTreeNode("IFAT Card List");

    /**
     * Creates new form DisplayGradeForm
     */
    public DisplayGradeForm() {
        initComponents();
    }

    public DisplayGradeForm(String path, Hashtable<String, StudentIFATCard> cards,
            int[] answers, int qnum, int bnum) {
        folderPath = path;
        studentCardTable = cards;
        answerKey = answers;
        questNum = qnum;
        boxNum = bnum;
        initComponents();
        loadNodes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_CardTree = new javax.swing.JTree();
        pnl_PrintContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        scroll_Results = new javax.swing.JScrollPane();
        pnl_CardResults = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnl_StudentInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_StdNo = new javax.swing.JTextField();
        txt_Course = new javax.swing.JTextField();
        txt_Grade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Export = new javax.swing.JButton();
        btn_Display = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grading Results");

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Title.setText("Grading Results");
        lbl_Title.setName("lbl_Title"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_CardTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_CardTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_CardTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tree_CardTree);

        pnl_PrintContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Assessment Results");

        javax.swing.GroupLayout pnl_CardResultsLayout = new javax.swing.GroupLayout(pnl_CardResults);
        pnl_CardResults.setLayout(pnl_CardResultsLayout);
        pnl_CardResultsLayout.setHorizontalGroup(
            pnl_CardResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        pnl_CardResultsLayout.setVerticalGroup(
            pnl_CardResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        scroll_Results.setViewportView(pnl_CardResults);

        jLabel7.setText("\"S\": Scratched box");

        jLabel8.setText("\"U\": Unscratched box");

        javax.swing.GroupLayout pnl_PrintContainerLayout = new javax.swing.GroupLayout(pnl_PrintContainer);
        pnl_PrintContainer.setLayout(pnl_PrintContainerLayout);
        pnl_PrintContainerLayout.setHorizontalGroup(
            pnl_PrintContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PrintContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addComponent(scroll_Results)
            .addGroup(pnl_PrintContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_PrintContainerLayout.setVerticalGroup(
            pnl_PrintContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PrintContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_Results, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PrintContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_StudentInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Name:");

        jLabel2.setText("Student No.");

        jLabel3.setText("Course:");

        jLabel4.setText("Grade:");

        txt_Name.setEditable(false);
        txt_Name.setName("txt_Name"); // NOI18N

        txt_StdNo.setEditable(false);
        txt_StdNo.setName("txt_StdNo"); // NOI18N

        txt_Course.setEditable(false);
        txt_Course.setName("txt_Course"); // NOI18N

        txt_Grade.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Student Information");

        javax.swing.GroupLayout pnl_StudentInfoLayout = new javax.swing.GroupLayout(pnl_StudentInfo);
        pnl_StudentInfo.setLayout(pnl_StudentInfoLayout);
        pnl_StudentInfoLayout.setHorizontalGroup(
            pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_StudentInfoLayout.createSequentialGroup()
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_StudentInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_StudentInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(txt_StdNo)
                    .addComponent(txt_Course)
                    .addComponent(txt_Grade))
                .addGap(325, 325, 325))
            .addGroup(pnl_StudentInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_StudentInfoLayout.setVerticalGroup(
            pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_StudentInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_StdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_StudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        btn_Export.setText("Export Results");
        btn_Export.setName("btn_Export"); // NOI18N
        btn_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportActionPerformed(evt);
            }
        });

        btn_Display.setText("View Card");
        btn_Display.setEnabled(false);
        btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DisplayActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");
        btn_Exit.setName("btn_Exit"); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_StudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_PrintContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Display)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Export)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnl_PrintContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_StudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Export)
                    .addComponent(btn_Display)
                    .addComponent(btn_Exit))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void tree_CardTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_CardTreeMouseClicked
        cardList = (DefaultMutableTreeNode) tree_CardTree.getSelectionPath().getLastPathComponent();
        filename = cardList.getUserObject().toString();
        StudentIFATCard card = studentCardTable.get(filename);
        int[][] cardArray = card.getCardArray();
        int[] scores = card.getScores();

        pnl_CardResults.removeAll();
        GridLayout gl = new GridLayout(questNum, boxNum + 2, 2, 2);
        pnl_CardResults.setLayout(gl);
        labels = new JLabel[questNum][boxNum];
        for (int i = 0; i < questNum; i++) {
            JLabel lbl_qNum = new JLabel();
            lbl_qNum.setText("Question " + (i + 1) + ": ");
            pnl_CardResults.add(lbl_qNum);
            for (int j = 0; j < boxNum; j++) {
                if(cardArray[i][j] == 0){
                    labels[i][j] = new JLabel("U");
                }else{
                    labels[i][j] = new JLabel("S");
                }
                pnl_CardResults.add(labels[i][j]);
            }
            JLabel lbl_score = new JLabel();
            lbl_score.setText("Score: " + scores[i] + "%");
            pnl_CardResults.add(lbl_score);
        }
        pnl_CardResults.revalidate();
        pnl_CardResults.repaint();
        
        txt_Course.setText(card.getCourse());
        txt_Grade.setText(card.getGrade()+ "%");
        txt_Name.setText(card.getStudentName());
        txt_StdNo.setText(card.getStudentNo() + "");
        imgCard = card.getBuffImage();
        btn_Display.setEnabled(true);
    }//GEN-LAST:event_tree_CardTreeMouseClicked

    private void btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DisplayActionPerformed
        StudentIFATCard card = studentCardTable.get(filename);
        DisplayCardForm dc = new DisplayCardForm(card);
        dc.setVisible(true);
    }//GEN-LAST:event_btn_DisplayActionPerformed

    private void btn_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportActionPerformed
        close();
        ExportForm ex = new ExportForm(studentCardTable);
        ex.setVisible(true);
    }//GEN-LAST:event_btn_ExportActionPerformed
    public void loadNodes() {
        Enumeration enu = studentCardTable.keys();
        while (enu.hasMoreElements()) {
            cardList.add(new DefaultMutableTreeNode(enu.nextElement()));
        }
        cardTreeModel = (DefaultTreeModel) tree_CardTree.getModel();
        cardTreeModel.setRoot(cardList);
        tree_CardTree.setModel(cardTreeModel);
    }
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayGradeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Display;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pnl_CardResults;
    private javax.swing.JPanel pnl_PrintContainer;
    private javax.swing.JPanel pnl_StudentInfo;
    private javax.swing.JScrollPane scroll_Results;
    private javax.swing.JTree tree_CardTree;
    private javax.swing.JTextField txt_Course;
    private javax.swing.JTextField txt_Grade;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_StdNo;
    // End of variables declaration//GEN-END:variables
}
