
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author YahMa
 */
public class LoadingForm extends javax.swing.JFrame {
    
    String folderpath;
    Hashtable<String, StudentIFATCard> studentCardTable;
    IFATController controller;
    DefaultTreeModel cardTreeModel;
    DefaultMutableTreeNode cardList = new DefaultMutableTreeNode("IFAT Card List");
    
    /**
     * Creates new form LoadingForm
     */
    public LoadingForm() {
        initComponents();
    }
    public LoadingForm(String path){
        initComponents();
        controller = new IFATController();
        try {
            folderpath = path;
            studentCardTable = controller.loadCards(path);
            loadNodes();
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        lbl_Image = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_CardTree = new javax.swing.JTree();
        lbl_FilePath = new javax.swing.JLabel();
        txt_Filepath = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_Info = new javax.swing.JLabel();
        lbl_Fname = new javax.swing.JLabel();
        lbl_Lname = new javax.swing.JLabel();
        txt_Fname = new javax.swing.JTextField();
        txt_Lname = new javax.swing.JTextField();
        lbl_StdNo = new javax.swing.JLabel();
        txt_StdNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Course = new javax.swing.JTextField();
        btn_Confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imported Card Preview");

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Title.setText("Imported Card List");
        lbl_Title.setName("lbl_Title"); // NOI18N

        btn_Back.setText("Back");
        btn_Back.setName("btn_back"); // NOI18N
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        lbl_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_Image.setName("lbl_Image"); // NOI18N

        btn_Exit.setText("Exit");
        btn_Exit.setName("btn_Exit"); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Next.setText("Next");
        btn_Next.setName("btn_Next"); // NOI18N
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_CardTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_CardTree.setName("tree_CardTree"); // NOI18N
        tree_CardTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree_CardTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tree_CardTree);

        lbl_FilePath.setText("Filepath:");
        lbl_FilePath.setName("lbl_filepath"); // NOI18N

        txt_Filepath.setEditable(false);
        txt_Filepath.setText("C://filepath");
        txt_Filepath.setMaximumSize(new java.awt.Dimension(64, 22));
        txt_Filepath.setName("txt_Filepath"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Info.setText("Edit Student Information");
        lbl_Info.setName("lbl_Info"); // NOI18N

        lbl_Fname.setText("First Name:");

        lbl_Lname.setText("Last Name:");

        txt_Fname.setEnabled(false);
        txt_Fname.setName("txt_Fname"); // NOI18N
        txt_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FnameActionPerformed(evt);
            }
        });

        txt_Lname.setEnabled(false);
        txt_Lname.setName("txt_Lname"); // NOI18N

        lbl_StdNo.setText("Student No.");

        txt_StdNo.setEnabled(false);
        txt_StdNo.setName("txt_StdNo"); // NOI18N

        jLabel1.setText("Course:");

        txt_Course.setEnabled(false);
        txt_Course.setName("txt_Course"); // NOI18N

        btn_Confirm.setText("Confirm");
        btn_Confirm.setEnabled(false);
        btn_Confirm.setName("btn_Confirm"); // NOI18N
        btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Course))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_StdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_StdNo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Fname))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Lname)))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_Confirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Info)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fname)
                    .addComponent(txt_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Lname)
                    .addComponent(txt_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_StdNo)
                    .addComponent(txt_StdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_Confirm)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Filepath, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Exit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Back)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Next))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_FilePath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Back)
                            .addComponent(btn_Exit)
                            .addComponent(btn_Next)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        close();
        WelcomeForm wf = new WelcomeForm();
        wf.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void tree_CardTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree_CardTreeMouseClicked
        cardList = (DefaultMutableTreeNode)tree_CardTree.getSelectionPath().getLastPathComponent();
        String filename = cardList.getUserObject().toString();
        StudentIFATCard card = studentCardTable.get(filename);
        txt_Filepath.setText(card.getFilePath());
        displayCard(card);
        btn_Confirm.setEnabled(true);
        txt_Fname.setEnabled(true);
        txt_Lname.setEnabled(true);
        txt_StdNo.setEnabled(true);
        txt_Course.setEnabled(true);
        txt_Fname.setText("");
        txt_Lname.setText("");
        txt_StdNo.setText("");
        txt_Course.setText("");
    }//GEN-LAST:event_tree_CardTreeMouseClicked

    private void txt_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FnameActionPerformed

    private void btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmActionPerformed
        cardList = (DefaultMutableTreeNode)tree_CardTree.getSelectionPath().getLastPathComponent();
        String filename = cardList.getUserObject().toString();
        StudentIFATCard card = studentCardTable.get(filename);
        
        String fname;
        String lname;
        String course;
        String stdNo;
        try {
            if(btn_Confirm.isEnabled()){
                fname = txt_Fname.getText();
                lname = txt_Lname.getText();
                course = txt_Course.getText();
                stdNo = txt_StdNo.getText();
                
                card.setStudentName(fname + " " + lname);
                card.setCourse(course);
                card.setStudentNO(Integer.parseInt(stdNo));
                
                studentCardTable.put(filename, card);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_ConfirmActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        close();
        ConfigureForm cf = new ConfigureForm(folderpath,studentCardTable);
        cf.setVisible(true);
    }//GEN-LAST:event_btn_NextActionPerformed
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    public void loadNodes(){
        Enumeration enu = studentCardTable.keys();
        while(enu.hasMoreElements()){
            cardList.add(new DefaultMutableTreeNode(enu.nextElement()));
        }
        cardTreeModel = (DefaultTreeModel)tree_CardTree.getModel();
        cardTreeModel.setRoot(cardList);
        tree_CardTree.setModel(cardTreeModel);
    }
    public void displayCard(StudentIFATCard card){
        BufferedImage img = card.getBuffImage();
        ImageIcon cardImage = new ImageIcon(img);
        lbl_Image.setIcon(cardImage);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_FilePath;
    private javax.swing.JLabel lbl_Fname;
    private javax.swing.JLabel lbl_Image;
    private javax.swing.JLabel lbl_Info;
    private javax.swing.JLabel lbl_Lname;
    private javax.swing.JLabel lbl_StdNo;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JTree tree_CardTree;
    private javax.swing.JTextField txt_Course;
    private javax.swing.JTextField txt_Filepath;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Lname;
    private javax.swing.JTextField txt_StdNo;
    // End of variables declaration//GEN-END:variables
}
