import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowEvent;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import org.opencv.core.Core;

import nu.pattern.OpenCV;

import java.awt.image.BufferedImage;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;



/**
 *
 * @author YahMa
 */
public class WelcomeForm extends javax.swing.JFrame {
	


    /**
     * Creates new form WelcomeForm
     */
    String path;
    private final JFileChooser fc;
    public WelcomeForm() {
        initComponents();
        fc = new JFileChooser();
        
        /* uncomment the next line and add an absolute path to set the default 
        directory when the open file dialog runs. It saves you from manually
        navigating to the folder with the images each time the application runs
        though this is strictly optional and the app still functions without it.
        */
        //fc.setCurrentDirectory(new File(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgp_RDBGroup = new javax.swing.ButtonGroup();
        lbl_Title = new javax.swing.JLabel();
        lbl_Desc = new javax.swing.JLabel();
        pnl_Selector = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        lbl_Select = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        btn_PDF = new javax.swing.JButton();
        btn_Folder = new javax.swing.JButton();
        lbl_Pathlabel = new javax.swing.JLabel();
        btn_Next = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        txt_filepath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IFAT Assessment Grading Application");

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Title.setText("Welcome to the IFAT Card Grading Application");
        lbl_Title.setName("lbl_Title"); // NOI18N

        lbl_Desc.setText("Welcome to the IFAT Card Grading Application. Select a pdf file or an image folder to get started.");
        lbl_Desc.setName(""); // NOI18N

        pnl_Selector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bgp_RDBGroup.add(jRadioButton1);
        jRadioButton1.setText("Import cards from pdf file.");
        jRadioButton1.setName("rdb_pdf"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        lbl_Select.setText("Select a method to import the IFAT cards into the application.");
        lbl_Select.setName("lbl_Select"); // NOI18N

        bgp_RDBGroup.add(jRadioButton2);
        jRadioButton2.setText("Import cards from image folder");
        jRadioButton2.setName("rdb_image"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btn_PDF.setText("Select pdf file");
        btn_PDF.setEnabled(false);
        btn_PDF.setName("btn_PDF"); // NOI18N
        btn_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PDFActionPerformed(evt);
            }
        });

        btn_Folder.setText("Select image folder");
        btn_Folder.setEnabled(false);
        btn_Folder.setName("btn_Folder"); // NOI18N
        btn_Folder.setOpaque(true);
        btn_Folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_SelectorLayout = new javax.swing.GroupLayout(pnl_Selector);
        pnl_Selector.setLayout(pnl_SelectorLayout);
        pnl_SelectorLayout.setHorizontalGroup(
            pnl_SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SelectorLayout.createSequentialGroup()
                .addGroup(pnl_SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_SelectorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_Select))
                    .addGroup(pnl_SelectorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnl_SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_SelectorLayout.createSequentialGroup()
                                .addComponent(btn_Folder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_PDF)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        pnl_SelectorLayout.setVerticalGroup(
            pnl_SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SelectorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_Select)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnl_SelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PDF)
                    .addComponent(btn_Folder))
                .addGap(15, 15, 15))
        );

        lbl_Pathlabel.setText("Filepath: ");

        btn_Next.setText("Next");
        btn_Next.setEnabled(false);
        btn_Next.setName("btn_Next"); // NOI18N
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");
        btn_Exit.setName("btn_Exit"); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        txt_filepath.setEditable(false);
        txt_filepath.setText("C://filepath");
        txt_filepath.setName("txt_filepath"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_Exit)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_Next))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_Pathlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_filepath))
                                .addComponent(pnl_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbl_Desc)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnl_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Pathlabel)
                    .addComponent(txt_filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Next)
                    .addComponent(btn_Exit))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            btn_PDF.setEnabled(true);
            btn_Folder.setEnabled(false);
            txt_filepath.setText("C://filepath");
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()){
            btn_PDF.setEnabled(false);
            btn_Folder.setEnabled(true);
            txt_filepath.setText("C://filepath");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void btn_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PDFActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            txt_filepath.setText(selectedFile.getPath());

            try {
                // Convert PDF to BufferedImage
                PDDocument document = Loader.loadPDF(selectedFile);
                PDFRenderer renderer = new PDFRenderer(document);

                int numPages = document.getNumberOfPages();
           	    BufferedImage[] pdfPages = new BufferedImage[numPages]; // Array to store pages of PDF as BufferedImage
             
                
                // Iterate through each page and render as BufferedImage
                for (int i = 0; i < numPages; i++) {
                    pdfPages[i] = renderer.renderImage(i);
                    
                } 
                //delete all files in "image" folder
                File dir = new File("./Images");
                for(File file: dir.listFiles()) {
                    if (!file.isDirectory()) {
                        file.delete();}
                }
                for (int i = 0; i < numPages; i++) {
                	
                //	write to image folder
                	ImageIO.write(pdfPages[i], "png", new File("./Images/image"+(i+1)+".png"));
                	
                }
                path = ("./Images");
             
                document.close();
                
                
                
                btn_Next.setEnabled(true);
                
            } catch (Exception e) {
            	txt_filepath.setText("Failed to load file");
            }
        }else{
            txt_filepath.setText("No File chosen");
        }
    }//GEN-LAST:event_btn_PDFActionPerformed
    
    
    

    private void btn_FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FolderActionPerformed
        
        
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnval = fc.showOpenDialog(this);
        if(returnval == JFileChooser.APPROVE_OPTION){
            try {
                File file = fc.getSelectedFile();
                path = file.getPath();
                txt_filepath.setText(path);
                btn_Next.setEnabled(true);
            } catch (Exception e) {
                txt_filepath.setText("Failed to load folder");
            }
        }else{
            txt_filepath.setText("No File chosen");
        }
    }//GEN-LAST:event_btn_FolderActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        close();
        LoadingForm lf = new LoadingForm(path);
        lf.setVisible(true);
    }//GEN-LAST:event_btn_NextActionPerformed
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        OpenCV.loadLocally();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgp_RDBGroup;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Folder;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_PDF;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lbl_Desc;
    private javax.swing.JLabel lbl_Pathlabel;
    private javax.swing.JLabel lbl_Select;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pnl_Selector;
    private javax.swing.JTextField txt_filepath;
    // End of variables declaration//GEN-END:variables
}
